# action.yml
name: 'Encrypt secret'
description: 'Build a secret using Libsodium tool'
inputs:
  public-key:
    description: 'A base 64 public key'
    required: true
  secret-input:  # id of input
    description: 'Text plain to secret'
    required: true
outputs:
  secret-output: # id of output
    description: 'The secret encrypted by libsodium'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.public-key }}
    - ${{ inputs.secret-input }}

